# Generated by Django 5.0 on 2025-09-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='stastus',
            new_name='status',
        ),
    ]
